[package]
org = "ballerinai"
name = "observe"
version = "1.6.0"
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/observe-internal-native-1.6.0.jar"
