[package]
org = "ballerinai"
name = "observe"
version = "1.7.0"
distribution = "2201.13.2"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/observe-internal-native-1.7.0.jar"
