[package]
org = "ballerinai"
name = "observe"
version = "1.1.0"
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/observe-internal-native-1.1.0-SNAPSHOT.jar"
